import "@src/styles/globals.css";

import { Header } from "@src/modules/shared/components/Header";
import Providers from "@src/modules/shared/providers/providers";
import { type Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "T3 PokeAPI",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const nunito = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body className="bg-background relative z-10 flex min-h-screen flex-col text-gray-800">
        <Header />
        <main className="relative flex w-full flex-grow flex-col">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
